import { AccessoriseTemplate } from './accessorise-template';

export const ACCESSORISE: AccessoriseTemplate[] = [
    {id: 2001,
    h1: 'Дождевик',
    img: '../../assets/img/img_accessorise/rainHarvey.jpg',
    price: 1020,
    forHarvey: true,
    forCharley: true,
    forCharleyMini: true,
    forBuggyXs: true,
    forBuggyEw: true,
    forBuggyMini: true
},
    {id: 2002,
    h1: 'Подстаканник оригинальный Easy Walker',
    img: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    price: 720,
    forHarvey: true,
    forCharley: true,
    forCharleyMini: true,
    forBuggyXs: true,
    forBuggyEw: true,
    forBuggyMini: true
},
    {id: 2003,
    h1: '2 в 1: подстаканник оригинальный Easy Walker + держатель для снеков',
    img: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    price: 900,
    forHarvey: true,
    forCharley: true,
    forCharleyMini: true,
    forBuggyXs: true,
    forBuggyEw: true,
    forBuggyMini: true
},
    {id: 2004,
    h1: 'Москитная сетка белого цвета Easy walker',
    img: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    price: 520,
    forHarvey: false,
    forCharley: false,
    forCharleyMini: false,
    forBuggyXs: false,
    forBuggyEw: true,
    forBuggyMini: false
},
    {id: 2005,
    h1: 'Москитная сетка белого цвета для линейки MINI buggy',
    img: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    price: 540,
    forHarvey: false,
    forCharley: false,
    forCharleyMini: false,
    forBuggyXs: false,
    forBuggyEw: false,
    forBuggyMini: true
},
    {id: 2006,
    h1: 'Москитная сетка белого цвета для линейки XS Buggy',
    img: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    price: 918,
    forHarvey: false,
    forCharley: false,
    forCharleyMini: false,
    forBuggyXs: true,
    forBuggyEw: false,
    forBuggyMini: false
},
    {id: 2007,
    h1: 'Сумка для переноски EW Buggy XS',
    img: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    price: 1200,
    forHarvey: false,
    forCharley: false,
    forCharleyMini: false,
    forBuggyXs: true,
    forBuggyEw: false,
    forBuggyMini: false
},
    {id: 2008,
    h1: 'Сумка для переноски Easy Walker',
    img: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    price: 1080,
    forHarvey: false,
    forCharley: false,
    forCharleyMini: false,
    forBuggyXs: false,
    forBuggyEw: true,
    forBuggyMini: true
},
    {id: 2009,
    h1: 'Harvey Extension set Увеличительный блок позволяющий использовать коляску для двойни или погодок',
    img: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    price: 3690,
    forHarvey: true,
    forCharley: false,
    forCharleyMini: false,
    forBuggyXs: false,
    forBuggyEw: false,
    forBuggyMini: false
},
    {id: 2010,
    h1: 'Москитная сетка Harvey',
    img: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    price: 840,
    forHarvey: true,
    forCharley: false,
    forCharleyMini: false,
    forBuggyXs: false,
    forBuggyEw: false,
    forBuggyMini: false
}
]