import { AccessoriseTemplate } from './accessorise-template';

export const ACCESSORISE: AccessoriseTemplate[] = [
    {id: 2001,
    h1: 'Дождевик оригинальный Easy Walker',
    img: '../../assets/img/img_accessorise/raincoverXS.jpg',
    price: 1020,
    forHarvey: true,
    forCharley: true,
    forCharleyMini: true,
    forBuggyXs: true,
    forBuggyEw: true,
    forBuggyMini: true
},
    {id: 2002,
    h1: 'Подстаканник оригинальный Easy Walker',
    img: '../../assets/img/img_accessorise/cup_holder.jpg',
    price: 720,
    forHarvey: true,
    forCharley: true,
    forCharleyMini: true,
    forBuggyXs: true,
    forBuggyEw: true,
    forBuggyMini: true
},
    {id: 2003,
    h1: '2в1: подстаканник + держатель для снеков',
    img: '../../assets/img/img_accessorise/snaskTray.jpg',
    price: 900,
    forHarvey: true,
    forCharley: true,
    forCharleyMini: true,
    forBuggyXs: true,
    forBuggyEw: true,
    forBuggyMini: true
},
    {id: 2004,
    h1: 'Москитная сетка для линейки MINI buggy',
    img: '../../assets/img/img_accessorise/mosquito_netMINI.jpg',
    price: 540,
    forHarvey: false,
    forCharley: false,
    forCharleyMini: true,
    forBuggyXs: false,
    forBuggyEw: false,
    forBuggyMini: false
},
    {id: 2005,
    h1: 'Москитная сетка белого цвета для люльки',
    img: '../../assets/img/img_accessorise/mosquitoNetHarvey.jpg',
    price: 540,
    forHarvey: true,
    forCharley: true,
    forCharleyMini: true,
    forBuggyXs: false,
    forBuggyEw: false,
    forBuggyMini: false
},
    {id: 2006,
    h1: 'Москитная сетка для линейки XS Buggy',
    img: '../../assets/img/img_accessorise/mosquito_netXS.jpg',
    price: 918,
    forHarvey: false,
    forCharley: false,
    forCharleyMini: false,
    forBuggyXs: true,
    forBuggyEw: false,
    forBuggyMini: false
},
    {id: 2007,
    h1: 'Сумка для переноски EW Buggy XS',
    img: '../../assets/img/img_accessorise/transportBagXS.jpg',
    price: 1200,
    forHarvey: false,
    forCharley: false,
    forCharleyMini: false,
    forBuggyXs: true,
    forBuggyEw: false,
    forBuggyMini: false
},
    {id: 2008,
    h1: 'Сумка для переноски Easywalker',
    img: '../../assets/img/img_accessorise/transportBagEW.jpg',
    price: 1080,
    forHarvey: false,
    forCharley: false,
    forCharleyMini: false,
    forBuggyXs: false,
    forBuggyEw: true,
    forBuggyMini: true
},
    {id: 2009,
    h1: 'Увеличительный блок для линейки Harvey',
    img: '../../assets/img/img_accessorise/extension_set.jpg',
    price: 3690,
    forHarvey: true,
    forCharley: false,
    forCharleyMini: false,
    forBuggyXs: false,
    forBuggyEw: false,
    forBuggyMini: false
},
    {id: 2010,
    h1: 'Органайзер оригинальный Easy Walker',
    img: '../../assets/img/img_accessorise/organizer.jpg',
    price: 840,
    forHarvey: true,
    forCharley: false,
    forCharleyMini: false,
    forBuggyXs: false,
    forBuggyEw: false,
    forBuggyMini: false
}
]