import { ProductTemplate } from './product-template';

export const ALLBUGGYS: ProductTemplate[] = [
    {id: 101,
    sectionId: 1,
    type: 'buggy',
    model: 'disneyXS',
    h1: 'Прогулочная коляска-"книжка" Easywalker Disney XS Mickey Ornament',
    price: 8850,
    sex: 'boy',
    img1: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img2: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img3: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    seoText: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit omnis deleniti cumque rem mollitia similique reprehenderit? Rem deserunt voluptas dicta reprehenderit fugit officia ducimus distinctio inventore similique ipsam praesentium laborum ipsa ullam, temporibus, ex minus aperiam reiciendis aliquam delectus molestias. Inventore esse delectus quas velit veniam distinctio officia neque perferendis placeat recusandae sint fugiat, debitis vel voluptatibus eveniet voluptate nam. Neque cumque iusto quam quo, odio esse ratione architecto ut veniam! Nostrum temporibus tenetur porro commodi odit dicta consequatur sequi, ducimus dignissimos rem molestias labore dolorem voluptate quos reprehenderit quas placeat voluptatem ratione amet optio dolor ex a. Suscipit commodi quod perspiciatis reprehenderit nulla asperiores, sint optio. Laborum ex eius excepturi nesciunt quis. Voluptate vero ducimus ratione. Expedita, magni quidem! Veniam laboriosam nulla excepturi architecto modi nisi deleniti quas? Quidem nulla beatae id voluptas recusandae consequuntur repudiandae neque facere atque qui labore, temporibus sit deleniti reprehenderit a tempora maiores fuga.'
},
    {id: 102,
    sectionId: 1,
    type: 'buggy',
    model: 'disneyXS',
    h1: 'Прогулочная коляска-"книжка" Easywalker Disney XS Minnie Ornament',
    price: 8850,
    sex: 'girl',
    img1: '../../assets/img/img_product_disneyXs/Minnie.jpg',
    img2: '../../assets/img/img_product_disneyXs/Minnie.jpg',
    img3: '../../assets/img/img_product_disneyXs/Minnie.jpg',
    seoText: 'SEO text'
},
    {id: 103,
    sectionId: 1,
    type: 'buggy',
    model: 'disneyXS',
    h1: 'Прогулочная коляска-"книжка" Easywalker Disney XS Mickey Diamond',
    price: 8850,
    sex: 'all',
    img1: '../../assets/img/img_product_disneyXs/Diamond.jpg',
    img2: '../../assets/img/img_product_disneyXs/Diamond.jpg',
    img3: '../../assets/img/img_product_disneyXs/Diamond.jpg',
    seoText: 'SEO text'
},
    {id: 201,
    sectionId: 2,
    type: 'buggy',
    model: 'miniXs',
    h1: 'Прогулочная коляска-"книжка" Easywalker MINI Buggy XS Union Jack Classic',
    sex: 'all',
    img1: '../../assets/img/img_product_miniXs/UJ_Classic.jpg',
    img2: '../../assets/img/img_product_miniXs/UJ_Classic.jpg',
    img3: '../../assets/img/img_product_miniXs/UJ_Classic.jpg',
    price: 8670,
    seoText: 'SEO text'
},
    {id: 202,
    sectionId: 2,
    type: 'buggy',
    model: 'miniXs',
    h1: 'Прогулочная коляска-"книжка" Easywalker MINI Buggy XS Union Jack Vintage',
    sex: 'all',
    img1: '../../assets/img/img_product_miniXs/UJ_Vintage.jpg',
    img2: '../../assets/img/img_product_miniXs/UJ_Vintage.jpg',
    img3: '../../assets/img/img_product_miniXs/UJ_Vintage.jpg',
    price: 8670,
    seoText: 'SEO text'
},
    {id: 203,
    sectionId: 2,
    type: 'buggy',
    model: 'miniXs',
    h1: 'Прогулочная коляска-"книжка" Easywalker MINI Buggy XS LXRY Black',
    price: 8850,
    sex: 'all',
    img1: '../../assets/img/img_product_miniXs/LXRY_Black.jpg',
    img2: '../../assets/img/img_product_miniXs/LXRY_Black.jpg',
    img3: '../../assets/img/img_product_miniXs/LXRY_Black.jpg',
    seoText: 'SEO text',
    features: '<ul><li>1 feature</li></ul>'
},
    {id: 204,
    sectionId: 2,
    type: 'buggy',
    model: 'miniXs',
    h1: 'Прогулочная коляска-"книжка" Easywalker MINI Buggy XS Union Jack Vintage B&W',
    price: 8850,
    sex: 'all',
    img1: '../../assets/img/img_product_miniXs/UJ_BW.jpg',
    img2: '../../assets/img/img_product_miniXs/UJ_BW.jpg',
    img3: '../../assets/img/img_product_miniXs/UJ_BW.jpg',
    seoText: 'SEO text'
},
    {id: 301,
    sectionId: 3,
    type: 'buggy',
    model: 'easywalkerXs',
    h1: 'Прогулочная коляска-"книжка" Easywalker XS Monaco Apero',
    price: 7950,
    sex: 'girl',
    img1: '../../assets/img/img_product_easywalkerXs/monaco_apero_XS.jpg',
    img2: '../../assets/img/img_product_easywalkerXs/monaco_apero_XS.jpg',
    img3: '../../assets/img/img_product_easywalkerXs/monaco_apero_XS.jpg',
    seoText: 'SEO text'
},
    {id: 302,
    sectionId: 3,
    type: 'buggy',
    model: 'easywalkerXs',
    h1: 'Прогулочная коляска-"книжка" Easywalker XS Berlin Breakfast',
    price: 7950,
    sex: 'boy',
    img1: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    img2: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    img3: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    seoText: 'SEO text'
},
    {id: 401,
    sectionId: 4,
    type: 'buggy',
    model: 'miniBuggy',
    h1: 'Прогулочная коляска-"трость" Easywalker MINI Buggy Union Jack Classic',
    price: 8670,
    sex: 'all',
    img1: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    img2: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    img3: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    seoText: 'SEO text'
},

    {id: 402,
    sectionId: 4,
    type: 'buggy',
    model: 'miniBuggy',
    h1: 'Прогулочная коляска-"трость" Easywalker MINI Buggy Union Jack Vintage',
    price: 8670,
    sex: 'all',
    img1: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    img2: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    img3: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    seoText: 'SEO text'
},

{id: 403,
    sectionId: 4,
    type: 'buggy',
    model: 'miniBuggy',
    h1: 'Прогулочная коляска-"трость" Easywalker MINI Buggy Milky Jack',
    price: 8670,
    sex: 'all',
    img1: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    img2: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    img3: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    seoText: 'SEO text'
},
    {id: 501,
    sectionId: 5,
    type: 'stroller',
    model: 'harvey',
    h1: 'Коляска 2в1 Harvey 2.0 голубая',
    price: 25000,
    sex: 'boy',
    img1: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img2: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img3: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    seoText: 'Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.'
},
    {id: 502,
    sectionId: 5,
    type: 'stroller',
    model: 'harvey',
    h1: 'Коляска 2в1 Harvey 2.0 розовая',
    price: 25000,
    sex: 'girl',
    img1: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img2: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img3: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    seoText: 'Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.'
},
    {id: 503,
    sectionId: 5,
    type: 'stroller',
    model: 'harvey',
    h1: 'Коляска 2в1 Harvey 2.0 черная',
    price: 25000,
    sex: 'all',
    img1: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img2: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img3: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    seoText: 'Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.'
},
    {id: 601,
    sectionId: 6,
    type: 'stroller',
    model: 'charley',
    h1: 'Коляска 2в1 charley голубая',
    price: 23000,
    sex: 'boy',
    img1: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img2: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img3: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    seoText: 'Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.'
},
    {id: 602,
    sectionId: 6,
    type: 'stroller',
    model: 'charley',
    h1: 'Коляска 2в1 charley розовая',
    price: 23000,
    sex: 'girl',
    img1: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img2: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img3: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    seoText: 'Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.'
},
    {id: 601,
    sectionId: 6,
    type: 'stroller',
    model: 'charley',
    h1: 'Коляска 2в1 charley серая',
    price: 23000,
    sex: 'all',
    img1: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img2: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img3: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    seoText: 'Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.'
},
]


